version: "3.8"

services:
  mongo-db:
    image: mongo:4.4
    container_name: mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongodb:/data/db
    ports:
      - 27117:27017
volumes:
  mongodb:
